matrix:
- name: html and Markdown
  aspell:
    lang: en
  dictionary:
    wordlists:
    - .wordlist.txt
    encoding: utf-8
  pipeline:
  - pyspelling.filters.markdown:
  - pyspelling.filters.html:
      comments: true
      attributes:
      - title
      - alt
      ignores:
      - :matches(code, pre)
      - a:matches(.magiclink-compare, .magiclink-commit)
      - span.keys
      - :matches(.MathJax_Preview, .md-nav__link, .md-footer-custom-text, .md-source__repository, .headerlink, .md-icon)
  sources:
  - "website/blog/**/*.html"
  - "website/blog/**/*.md"
  - "website/blog/**/*.mdx"
  - "website/docs/**/*.mdx"
  - "website/docs/**/*.md"
  default_encoding: utf-8